version: "3.8"

services:

postgres:

image: postgres:15

container_name: agenda-db

environment:

POSTGRES_DB: agenda

POSTGRES_USER: postgres

POSTGRES_PASSWORD: postgres

ports:

"5432:5432"

backend:

build: ./backend

ports:

"8080:8080"

depends_on:

postgres

frontend:

build: ./frontend

ports:

"3000:3000"

depends_on:

backend